

GET http://localhost:3000/tasks

###

POST http://localhost:3000/task
Content-Type: application/json

{
    "title": "Wash Car",
    "description": "Wash the car",
    "status": "Completed"
}

###
GET http://localhost:3000/task/33e6a3ce-ae9f-42df-8c69-eaab974b4bcc

###
PUT http://localhost:3000/task/33e6a3ce-ae9f-42df-8c69-eaab974b4bcc
Content-Type: application/json

{
    "title": "Cleaning Car",
    "description": "Washing the car",
    "status": "Pending"
}

###
PATCH  http://localhost:3000/task/33e6a3ce-ae9f-42df-8c69-eaab974b4bcc
Content-Type: application/json

{
    "title": "ing Car",
    "description": "Washing the car",
    "status": "Pending"
}

###
DELETE http://localhost:3000/task/4324411e-d24f-4fca-b181-45fb289d6846